[package]
name = "imxrt-ccm"
version = "0.1.0"
authors = ["Ian McIntyre <ianpmcintyre@gmail.com>"]
edition = "2018"
description = """
Driver for the i.MX RT clock control module (CCM)
"""

[dependencies.imxrt-ral]
version = "0.4"
optional = true

[features]
imxrt1011 = []
imxrt1062 = []