name: Documentation

on:
  push:
    branches: [ master ]

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      name: Install toolchain
      with:
        toolchain: nightly
        profile: minimal
        override: true

    - name: Generate docs
      uses: actions-rs/cargo@v1
      with:
        command: rustdoc
        args: --features imxrt1060 --features imxrt-ral/imxrt1062 -- --cfg docsrs

    - name: Write redirect
      run: echo "<meta http-equiv=\"refresh\" content=\"0;url=imxrt_ccm\">" > target/thumbv7em-none-eabihf/doc/index.html

    - name: Deploy to GitHub pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: target/thumbv7em-none-eabihf/doc
        publish_branch: gh-pages
